services:
    kinerity.bestanswer.listener:
        class: kinerity\bestanswer\event\listener
        arguments:
            - '@auth'
            - '@dbal.conn'
            - '@controller.helper'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }

    kinerity.bestanswer.main.controller:
        class: kinerity\bestanswer\controller\main_controller
        arguments:
            - '@auth'
            - '@dbal.conn'
            - '@language'
            - '@log'
            - '@request'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
